language: node_js
node_js:
    - 11
    - 10
    - 9

sudo: false
install:
    - npm i

stages:
    -   name: test
        if: branch = master AND tag IS blank
    -   name: release
        if: branch = master AND tag IS blank

script: npm run lint && npm run test && if [[ "$(node -v)" = v10.* ]]; then npm run coverage; fi

jobs:
    include:
        -   stage: release
            node_js: 10
            script: |
                npm run build
                npx lerna publish
