language: node_js
node_js:
    - 10

sudo: false
install:
    - npm ci
    - lerna bootstrap

if: branch = master AND tag IS blank

script:
    - lerna run --parallel lint
    - lerna run --parallel build
    - lerna run --parallel test
    - lerna run --parallel coverage
